### ISSUE TITLE
Grafana support

### ISSUE THREAD

**Issue by hengfeiyang** [zinclabs/zincsearch#136]
Do you want zinc support Grafana?

If you like, please click 👍🏻

I will implement it if over 10 users  support.

**Comment by hengfeiyang** [comment]
Okay, i will implement it.

**Comment by hengfeiyang** [comment]
I already committed in the `support-grafana` branch.

https://github.com/zinclabs/zinc/tree/support-grafana

**Comment by bakman2** [comment]
Ok I can add zinc as a elastic datasource succesfully in grafana, but when clicking "explore", i get:

>Elasticsearch error: 404 page not found

**Comment by hengfeiyang** [comment]
First you should add some data into Zinc, because grafana will check the metadata of index.

In Grafana there has Some fields you should set:

1. HTTP -> URL: http://10.x.x.x:4080/es
2. Auth -> Basic auth: Enable
3. Auth -> Basic Auth Details, input username and password
4. Elasticsearch details
  1. Index name: input a specific index name or a index pattern like: `[log-]YYYY.MM.DD`
  2. select the pattern mode or no `pattern`
  3. Time field name: `@timestamp`
  4. Version: 7.0+
 
then `Save & Test`

**Comment by bakman2** [comment]
>HTTP -> URL: http://10.x.x.x:4080/es

The `/es` was the key to make it work. thanks.

**Comment by hengfeiyang** [comment]
Has merged in main branch.

**Comment by amirEBD** [comment]
I had tested Zinc's metrics which is working correctly. Is there a json file for Grafana support in the main branch?
[This](https://github.com/zinclabs/zinc/tree/support-grafana) branch is returning 404! @hengfeiyang

**Comment by hengfeiyang** [comment]
We have already merged in main branch. you can use it in release version.

**Comment by hengfeiyang** [comment]
I add some charts to Grafana, you can follow this link:

https://github.com/zinclabs/zinc/pull/407

**Comment by prabhatsharma** [comment]
Closing this issue. Look at https://github.com/zinclabs/zincsearch/issues/782 for explanation.
