### ISSUE TITLE
Playground

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch#167]
**Is your feature request related to a problem? Please describe.**
Currently in order to query from console we can use only querystring. Ability to use DSL and custom REST queries would provide a lot of flexibility.

**Describe the solution you'd like**
A playground that allows executing REST DSL/JSON requests directly form within console. 

**Describe alternatives you've considered**
Using postman/hoppscotch.io

**Comment by prabhatsharma** [comment]
![Image](https://user-images.githubusercontent.com/4242188/170765932-a83ce977-297e-4982-8ae6-63f41688f9b1.png)

**Comment by rolwin100** [comment]
working on it

**Comment by gedw99** [comment]
This would be really useful 

Can it be a bit like postman in that the new queries you make are saved in a config file , and you can change and delete existing ones. 


Then I can save that config file in any GitHub repo for later use

**Comment by hengfeiyang** [comment]
@rolwin100 there is a long time, maybe you are not working on it. If you not do it, we can let other user pick up it.

**Comment by prabhatsharma** [comment]
Closing it as stale
