### ISSUE TITLE
Failed to get timestamp filled in table correctly on Grafana

### ISSUE THREAD

**Issue by ADeeeee** [zinclabs/zincsearch#195]
Environments:

Grafana: v8.3.6
ZInc: 0.2.3
ZINC_PLUGIN_ES_VERSION=7.17.3
ElasticSearch: 7.9.1

Situation:

Grafana get the ```@timestamp``` field, but could only get *null*, even though it did showed in the result of the query.

![image](https://user-images.githubusercontent.com/35981633/172344829-5b27054e-7de7-43e4-948f-dcd51f326f20.png)

![image](https://user-images.githubusercontent.com/35981633/172344884-07d5b08f-bf31-45d6-8329-6daa8cd51831.png)

fluentbit parsers.log:

```
[PARSER]
    Name     nginx_error
    Format   regex
    Regex ^(?<time>\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2})......
    Time_Key time
    Time_Format %Y/%m/%d %H:%M:%S
 ```

The format of timestamp 

```
in Zinc:
  "@timestamp": "2022-06-07T09:05:53Z",

in ElasticSearch:
  "@timestamp": "2022-06-07T09:01:37.000Z",
```

Using the same config in fluentbit, resulted in two formats in different DBs and the ES one directly works on Grafana. I guess the date format is the root cause.

**Comment by bakman2** [comment]
> I know that, this is because:
es returns @timestamp in _source field,
zinc returns @timestamp in root path.

How do you resolve this issue ?

**Comment by prabhatsharma** [comment]
Closing with [PR 719](https://github.com/zinclabs/zincsearch/pull/719)
