### ISSUE TITLE
regular user can create admin

### ISSUE THREAD

**Issue by shaba** [zinclabs/zincsearch#250]
Hi.
User with Role=user can add user with Role=admin.

1. what is the difference user and admin roles?
2. i think regular user should can read/write logs, but not create new users or create new templates.
3. may be need more roles, for example search log only.

**Comment by prabhatsharma** [comment]
Currently all users have same privilege.  RBAC is still not implemented. I
will add it to the roadmap.

**Comment by prabhatsharma** [comment]
Closing it as its stale
