### ISSUE TITLE
I did a simple performance test of zinc and successfully created more than 60000 indexes. I found these problems:

### ISSUE THREAD

**Issue by xiaojun207** [zinclabs/zincsearch#257]
I did a simple performance test of zinc and successfully created more than 60000 indexes. I found these problems:
1. Search no longer returns data, nor does a single index return data. It may be the search data timeout, or it may be other;
2. The page load index list is all indexes. When there is a large amount of data, it cannot be loaded. (I am going to change this to search loading + paging loading);
3. When the zinc program starts, it takes 8632 milliseconds to start because all indexes need to be loaded;
4. It is also time-consuming for a zinc program to safely close threads, which may be similar to the third case;
5. In terms of concurrent processing of requests, because it is a native test, the pressure test program and zinc occupy resources at the same time, for reference only. I prepared 80000 requests, divided into 100 threads, and finally successfully created more than 60000 indexes. However, the average processing time of these requests is more than 4 seconds. Some requests were executed successfully, but did not return correctly.

**Comment by prabhatsharma** [comment]
@xiaojun207 Thanks for the tests. We are still test cases in the area of performance. We will add the test case of large number of indexes to our performance test scenario.

**Comment by prabhatsharma** [comment]
Can you also provide the details on hardware used for this test?

**Comment by xiaojun207** [comment]
> Can you also provide the details on hardware used for this test?

CPU: Inter core i7
Memory: 16g
During the test, the pressure test client is also on the same machine. There is no way to make a detailed judgment on the resources occupied by zinc, which is less than 1/3 of the hardware resources.
