### ISSUE TITLE
View surrounding documents (log entries / records)

### ISSUE THREAD

**Issue by DHFW** [zinclabs/zincsearch#270]
**Is your feature request related to a problem? Please describe.**
When I find i.e. the error message, I would like to know what logging entries are before the error message entry. Elastisch search has a UI where it will easily show the previous (and next) 5 entries. That is very helpful!

**Describe the solution you'd like**
When selecting a record, have the option to also fetch the previous or next 5 records. And from there you can also find the next 5 records and so on. Maybe my error message record has a leading 20 previous entries in the logs. I would like to fetch them all incrementally.
See this YouTube video explaining the feature I'm requesting: [view surrounding documents](https://youtu.be/sNGbxbCv-6I?t=51)

**Describe alternatives you've considered**
Alternative is find the records in the same time frame (before and after), but that is less convenient than my suggestion/feature request and requires more searching because in seconds many log records are generated.

**Additional context**
I'm working for a small organisation (sole developer) and we had to stop using Elastic stack because of it's high capacity requirements (problems with sharding requirements exceeded). We run it on 1 host in Docker with around 30 containers. So I'm very much looking forward to something like Zinc! But the requirement from this feature request is a big one holding me back for now.

**Comment by prabhatsharma** [comment]
Implemented in https://github.com/zinclabs/zincobserve
