### ISSUE TITLE
Zinc performance test vs. Elasticsearch

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zincsearch#349]
**What were you trying to achieve?**
I was trying to test zinc's performance vs elastic search.

**What action did you take?**
Create a single node elasticsearch cluster by docker. Create a zinc instance with docker.
After that I tried to make a big index in both and watched the resource usage of two containers. I used **_bulk** in both of them and a json file of **200 records** which will be executed by curl for **100000 times**.

**What action/response/output did you expect?**
I would expect the resource usage to be less than or equal elastic search's instance.

**What actually happened?**
This is the output made by _docker stats_ command:

**CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O         PIDS**
8aba1b07067f   elasticsearch   **4.57%**     1.531GiB / 31.33GiB   4.89%     713MB / 543MB   0B / 2.18GB       89
48798aa270c6   zincsearch      **142.02%**   123MiB / 31.33GiB     0.38%     714MB / 534MB   8.19kB / 27.6GB   12

The point is the cpu usage is varying in between 50%-150% but elastic is so much less than that in cpu usage.
Note: Also I have to mention that elasticsearch will initially get about 1.3GB memory 

**How to reproduce the issue?**

**What version of ZincSearch are you using?**
public.ecr.aws/zinclabs/zinc:latest

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**

**Which service(s) is this relate to?**
Core

**Comment by prabhatsharma** [comment]
Thanks @amirEBD . We will soon be covering this in #312

**Comment by amirEBD** [comment]
Thanks for your quick and well responding.
I had some other benchmarks running on Zinc vs. Elasticsearch single nodes.

Created an index of about 3GB identical data in both search engines.
I searched in both a specific term query and got this results:

**Zinc --> About 3s taken and constantly about 3s on earlier searches**
**Elastic --> About 2.5s taken and about 3ms for next queries**

From this I assume that there is no caching in Zinc till now. Do you have any suggestions for that?  @prabhatsharma

**Comment by prabhatsharma** [comment]
https://github.com/zinclabs/zinc/issues/351

**Comment by amirEBD** [comment]
Hi again! @prabhatsharma 
As we are testing zinc on diffrent scenarios and under diffrent **system specs** , I had tested zinc on **HDD vs SSD** drives.
Assuming zinc would not use memory often, so I had an opinion that HDD versus SSD drives will come into a huge diffrent latency (maybe at least 1/10), but indeed as I test them the output was quit a same! Could you please give me feedback if I was wrong about my first assumption? 

Testing Environment in both HDD Env and SSD Env:
- Create an index of about 20 GB in both. Searched same query.

Output:
- HDD: took 3.5s
- SSD: took 2.1s

**Comment by prabhatsharma** [comment]
Currently all reads happen sequentially. So there are going to be efficiencies of using SSD but not very significantly. We are working on parallelizing reads. This should result in significant speed benefits on SSDs. What is your current use case for which you are testing?

**Comment by amirEBD** [comment]
Thanks again for quick responding Prabhat,
We have a cluster of ES which contains about 5TB of data. The problem we face is the resource usage (mainly the memory usage). So we started a research for any compatible search engine which will use lower resources and also responds to our needs.
So I'm trying to test zinc under a few GB of data in an index and need for quick responding :))))

P.S.: We also have written the sharding side of ElasticSearch ourselves and probably no need for sharding/clustring stuff like Elastic have.
P.S: Our application is a messenger's search system :))

**Comment by prabhatsharma** [comment]
This is very interesting.

**Comment by amsjavan** [comment]
> This is very interesting.

What is your solution for such a scenario?

**Comment by prabhatsharma** [comment]
There can be 2 solutions.

1. Zinc provides a clustering mechanism. This is in progress in Zinc.
2. You handle clustering and sharding yourself. You are already doing it yourself. All Zincsearch  team needs to do is close some of the performance items we are working on.

**Comment by prabhatsharma** [comment]
No plans to do this in near future.
