### ISSUE TITLE
Add caching for recent queries to improve performance

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zincsearch#351]

**Comment by hritikb27** [comment]
hey I'm currently learning Go and would like to contribute to this issue with some guidance and assistance if possible :)

**Comment by prabhatsharma** [comment]
Sure, feel free to let us know if you have questions.

**Comment by hoslo** [comment]
> Sure, feel free to let us know if you have questions.

What layer should the cache be in? Do you have any advice

**Comment by prabhatsharma** [comment]
I think an appropriate place to store the cache data would be at zinc level. 

User ----API Call---->  Zinc ----> Bluge
Bluge ---> Zinc creates a cache layer and returns response -----> User

Zinc can create a new folder ("cache") and store results in their asynchronously.
result for each query can be in a filename which is hash of the query. contents of the file will be the result. Whenever a new query arrives, its cache can be calculated and if a file by that name exists then the results can be returned.

We will also need to worry about cache invalidation. We need to plan on what is the best way to invalidate result cache automatically. based on time? based on some other parameter? We may need an API to clear the cache manually too if the user chooses to do so.

**Comment by gedw99** [comment]
https://github.com/dtm-labs/rockscache is a goang based caching system using redis that is worth looking into.

**Comment by esatterwhite** [comment]
I would not want to run a search engine that relies on redis as a query cache. redis is rather difficult to scale horizontally. Not impossible, difficult and unpleasant. Our production search systems store terabytes of data and having to scale redis to keep up with our search solution isn't an attractive solution.

**Comment by hengfeiyang** [comment]
@esatterwhite  TB data, What type of the data, logs?

**Comment by esatterwhite** [comment]
> @esatterwhite TB data, What type of the data, logs?

Yes

**Comment by hengfeiyang** [comment]
> > @esatterwhite TB data, What type of the data, logs?
> 
> Yes

Welcome to test our new production focus log solution. https://cloud.zincsearch.com

And will open-source soon.

**Comment by esatterwhite** [comment]
With all. Of our compliance restrictions across 20.different environments we basically have to run on premise
