### ISSUE TITLE
Option to specify a subpath/path prefix

### ISSUE THREAD

**Issue by weslambert** [zinclabs/zincsearch#37]
Thanks for your work on this!

It would be great to be able to specify a subpath, or path prefix to be used, for hosting behind a reverse proxy.

For example. if I wanted to proxy `:4080/ui`, and have it accessible as `/zinc/ui`

**Comment by prabhatsharma** [comment]
Latest release https://gallery.ecr.aws/prabhat/zinc, https://github.com/prabhatsharma/zinc/releases/tag/v0.1.4 should help. Let me know how it goes.

**Comment by prabhatsharma** [comment]
Here is a working example of nginx ingress subpath - https://github.com/prabhatsharma/zinc/blob/main/k8s/ingress-subpath.yaml

**Comment by mamcx** [comment]
How do this in plain nginx?

**Comment by hengfeiyang** [comment]
Just like this:

```
server {
    listen                 80;
    proxy_connect_timeout 60s;
    proxy_read_timeout    60s;
    proxy_send_timeout    60s;
    
    server_name  _;
    index index.html;
    root /usr/share/nginx/html;

    location /what-you-want/ {
        add_header Access-Control-Allow-Origin *;
        proxy_set_header Host $host;
        proxy_set_header Origin-Host $host;
        proxy_set_header Origin-URI $request_uri;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass       http://127.0.0.1:4080/;
    }
}

```

**Comment by mamcx** [comment]
Thanks!.
