### ISSUE TITLE
Sort values on ES api

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zincsearch#419]
**Is your feature request related to a problem? Please describe.**
As I wan't to transport my elasticsearch cluster to zinc, having ES compatible API will help alot. Another inconsistency between the Elastic and zinc is **Sort values**. As Elastic will return the sorted values on responses having the sort field.
This can be seen on elasticsearch documentation [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#_sort_values_2) .
@hengfeiyang

**Comment by amirEBD** [comment]
{
        "_index" : "my_index",
        "_type" : "_doc",
        "_id" : "YTI2MGM1Y2IwNTUyYzU0NDI3MTczMWIyMGU1MGI4Mzg=",
        "_score" : null,
        "_source" : {
          "tie_breaker_id" : "YTI2MGM1Y2IwNTUyYzU0NDI3MTczMWIyMGU1MGI4Mzg=",
          "date" : "2022-07-06T12:15:14.978Z",
          "message" : "test",
        },
        "sort" : [
          1657109714978,
          "YTI2MGM1Y2IwNTUyYzU0NDI3MTczMWIyMGU1MGI4Mzg="
        ]
}

**Comment by hengfeiyang** [comment]
We supported most commonly API fro ES, not 100%, and about your question, Maybe need some times to do that.
