### ISSUE TITLE
URL path is being added on refresh

### ISSUE THREAD

**Issue by jonatan5524** [zinclabs/zincsearch#434]
Note: Any issue that does not follow below template will be closed without consideration. You may remove this line when filing issue.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Refresh a page
**What action did you take?**
Hit the refresh button of the browser
**What action/response/output did you expect?**
Getting the same URL:
![image](https://user-images.githubusercontent.com/37303618/184492669-2217f327-86a8-4b77-a2b4-fcba92e9091a.png)

**What actually happened?**
![image](https://user-images.githubusercontent.com/37303618/184492685-75ce9d2e-8533-4b32-b778-a4bc69e9fa0d.png)

**How to reproduce the issue?**
Hit refresh multiple times and it will add the path:
![image](https://user-images.githubusercontent.com/37303618/184492713-00ec894d-24cf-43c5-a4f3-69cb7a0ab44a.png)

**What version of ZincSearch are you using?**
v0.2.8 latest version on development 
**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
Using the Brave browser
go version go1.18.1 linux/amd64
node version v16.15.1
**Any attachments/screenshots?**

**Which service(s) is this relate to?**
GUI

**Comment by hengfeiyang** [comment]
Yes, you are right, but it just in local develop mode. if you use http://localhost:4080, we handled it.

In UI develop mode, i know that, but i am not sure how to fix it. and it not effect working. so i leave it.

Maybe you can try to fix it? Welcome contribute PR to zinc.

**Comment by jonatan5524** [comment]
I will at it, if you say it's only in dev in UI maybe this is something in vue3.
