### ISSUE TITLE
Zinc Analyzers

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zincsearch#441]
**What were you trying to achieve?**
The problem we face is in **analyzer** side of Zinc. As I want to have such analyzer as below which is accepted by Zinc and also works properly on Elastic cluster.
```
POST /api/index
{
    "name": "test",
    "storage_type": "disk",
    "shard_num": 1,
    "settings": {
      "analysis": {
        "char_filter": {
          "space_hashtags": {
            "type": "mapping",
            "mappings": [
              "# => |#",
              "_ => -"
            ]
          }
        },
        "filter": {
          "hashtag_as_alphanum": {
            "type": "english_possessive_stemmer",
            "type_table": [
              "# => ALPHANUM",
              "@ => ALPHANUM"
            ]
          }
        },
        "analyzer": {
          "my_analyzer": {
            "tokenizer": "whitespace",
            "type": "custom",
            "char_filter": [
              "space_hashtags"
            ],
            "filter": [
              "lowercase",
              "hashtag_as_alphanum"
            ]
          }
        }
      }
    }
  }
```

As I tested the functionality the "hashtag_as_alphanum" was not applied. Is it supported for now?

**Comment by prabhatsharma** [comment]
hashtag_as_alphanum is not supported in zinc.

**Comment by amirEBD** [comment]
Thanks for quick responding @prabhatsharma,
Indeed it is just a name. I just meant that **custom analyzers** like hashtag_as_alphanum are supported or not?
PS. As your answer I tought you've considered it as a type.

**Comment by hengfeiyang** [comment]
We support custom analyzers, like:

```
{
  "analysis": {
    "analyzer": {
      "suosi_standard": {
        "char_filter": [
          "suosi_char_filter"
        ],
        "tokenizer": "standard",
        "token_filter": [
          "lowercase"
        ]
      }
    },
    "char_filter": {
      "suosi_char_filter": {
        "type": "mapping",
        "mappings": [
          "，  => -",
          "。  => -",
          "、  => -",
          "？  => -",
          "！  => -",
          "；  => -"
        ]
      }
    }
  }
}
```

https://docs.zincsearch.com/api/index/analyze/#support-charfilters

**Comment by amirEBD** [comment]
Thanks indeed, So as your explanation I got that you don't support **custom token filters**.
One of the most important token filters is **word delimiter** that is essential for custom token filters. As you can assume `type_tables` for non-alphanumeric characters.

**Comment by hengfeiyang** [comment]
Yes, for now, we not supported `type_tables`
