### ISSUE TITLE
Data directory permissions on Windows (docker)

### ISSUE THREAD

**Issue by marvijo-code** [zinclabs/zincsearch#454]
Hi. I'm on a Windows host with Docker running Linux containers. When I execute the docker command:

docker run -it public.ecr.aws/h9e2j3o7/zinc:0.2.9 -v "C:\dev\zinc-search\data":/data -e ZINC_DATA_PATH=/data -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin

I get:
{"level":"debug","time":"2022-08-24T10:15:56Z","message":"open .env: no such file or directory"}
{"level":"fatal","error":"mkdir data: permission denied","time":"2022-08-24T10:15:56Z","message":"ZINC_DATA_PATH is not writable"}

Linked to the Linux solution for issue #187

**Comment by Nash-x9** [comment]
Based on your error message, it looks like you put the volume in C-Drive, which is not a good way to use it, and it is recommended that you set the volume on a non-system drive.
Other WinDocker tips: https://docs.docker.com/desktop/windows/permission-requirements/

**Comment by marvijo-code** [comment]
@Nash-x9 Drive G doesn't work as well:

![image](https://user-images.githubusercontent.com/82562019/186479450-677131fe-ff27-4734-9618-14295ff7ad8e.png)

This was never an issue with other docker container volumes. I also tried the docker command without a mapped volume, same error. It should default ZINC_DATA_DIRECTORY to ./data.

**Comment by alexander-schranz** [comment]
In my case I could solve it by cleaning my docker builder caches #710:

```bash
docker builder prune
```
