### ISSUE TITLE
go-elasticsearch example doesn't work

### ISSUE THREAD

**Issue by iangudger** [zinclabs/zincsearch#475]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Run the `go-elasticsearch` [example](https://github.com/elastic/go-elasticsearch/blob/5653c7576e1e5ad7a4614af7bdacfcb1a95880e0/_examples/main.go)

**What action did you take?**
Modified the example to talk to Zinc (`http://localhost:4080/es`) with appropriate credentials. Run the example.

**What action/response/output did you expect?**
Two hits to be printed.

**What actually happened?**
No errors, but zero hits were found.

**How to reproduce the issue?**

1. Start Zinc
2. Modify [example](https://github.com/elastic/go-elasticsearch/blob/5653c7576e1e5ad7a4614af7bdacfcb1a95880e0/_examples/main.go) to connect to Zinc
3. Run example

**What version of ZincSearch are you using?**
v0.3.0

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**

**Which service(s) is this relate to?**
API

**Comment by hengfeiyang** [comment]
I tested the example, You just need change one line, because we response not compatible es.

you can change this line:
```
log.Printf("[%s] %s; version=%d", res.Status(), r["result"], int(r["_version"].(float64)))
```

to

```
log.Printf("[%s] data=%v\n", res.Status(), r)
```

And use NewClient with config:

```
cfg := elasticsearch.Config{
		Addresses: []string{"http://localhost:4080/es/"},
		Username:  "admin",
		Password:  "Complexpass#123",
	}
	es, err := elasticsearch.NewClient(cfg)

```

It can works.

**Comment by iangudger** [comment]
Since elasticsearch compatibility is a goal, shouldn't this be fixed? Should I try to put together a PR?

**Comment by hengfeiyang** [comment]
Good question, let us think about it.

**Comment by hengfeiyang** [comment]
We have announce new release v0.3.1, you can have a try.

**Comment by iangudger** [comment]
I tried `v0.3.2` and it still isn't working. Same zero results.

**Comment by hengfeiyang** [comment]
we took async write to index, maybe need 1 second later, you can search the data, or you can run the example again, you will got the results.
