### ISSUE TITLE
CPU/RAM Ratio

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zincsearch#481]
I put Zinc on production levels with docker container. The average load on zinc is about 100 insert/sec with the batch mode.
Firstly the container had **8 cores and 16 GBs of RAM** (The usage was about 4-6 GB). Because of a migration running, I had to increase the **cores to 32** . Unexpectedly the RAM usage increased rapidly to full 16 GBs. Is there a ratio between cores to memory space? What is the reason for such performance?

**Comment by hengfeiyang** [comment]
How many documents do you have for now, and what is the size of you data already ingested?

**Comment by amirEBD** [comment]
There are 1500 indices with volume of 2GB.
The docs count is about 1M docs.

**Comment by hengfeiyang** [comment]
You have 1500 indices, Maybe this is the problem. We keep each index metadata in memory. We plan to implement a feature close inactive index after 10 minutes, but haven't. 

Can you try restart zinc, Does the memory usage down?

**Comment by amirEBD** [comment]
I increased the memory usage to 64 GBs and zinc stoped at 45 GBs. Then restarted the zinc and it stoped on 35 GBs.
But after doing some searches on zinc, it crashed. I guess it is because of out of memory issues but not sure. Why such scenario happend?
PS. Zinc logged this for me:
```
goroutine 256812 [runnable]:
syscall.Syscall(0x4a, 0x327d, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.Fsync(0x0?)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:423 +0x30
internal/poll.(*FD).Fsync.func1(...)
	/usr/local/go/src/internal/poll/fd_fsync_posix.go:18
internal/poll.ignoringEINTR(...)
	/usr/local/go/src/internal/poll/fd_posix.go:74
internal/poll.(*FD).Fsync(0xc03ec08368?)
	/usr/local/go/src/internal/poll/fd_fsync_posix.go:17 +0xf4
os.(*File).Sync(0xc03ec08368)
	/usr/local/go/src/os/file_posix.go:168 +0x4e
github.com/zinclabs/zinc/pkg/wal/redo.(*Log).Write(0xc05f26e190, 0x1, {0xc0e5315ca8, 0x9, 0x2?})
	/go/src/github.com/zinclabs/zinc/pkg/wal/redo/redo.go:126 +0x3b3
github.com/zinclabs/zinc/pkg/core.(*IndexShard).writeRedoLog(0xc001c15a40, 0xc3c078e7b0?, 0x4178f3?, 0x1419f80?)
	/go/src/github.com/zinclabs/zinc/pkg/core/index_shards_wal.go:250 +0xbe
github.com/zinclabs/zinc/pkg/core.(*IndexShard).ConsumeWAL(0xc001c15a40)
	/go/src/github.com/zinclabs/zinc/pkg/core/index_shards_wal.go:210 +0x7ce
github.com/zinclabs/zinc/pkg/core.(*IndexShardWALList).ConsumeWAL.func1()
	/go/src/github.com/zinclabs/zinc/pkg/core/index_shards_wallist.go:96 +0x4e
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20220601150217-0de741cfad7f/errgroup/errgroup.go:72 +0xa5

goroutine 256908 [runnable]:
internal/poll.runtime_pollWait(0x7f6ccd773f38, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc44ec4de00?, 0xc4f5e24000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc44ec4de00, {0xc4f5e24000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc44ec4de00, {0xc4f5e24000?, 0xc007c866a0?, 0x6d7a05?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc04e0fa0c0, {0xc4f5e24000?, 0xc007c866e0?, 0x12b8165?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc6dc75ddd0, {0xc4f5e24000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc7ff42e420)
	/usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc7ff42e420, 0x0?)
	/usr/local/go/src/bufio/bufio.go:371 +0x2f
bufio.(*Reader).ReadLine(0xc7ff42e420)
	/usr/local/go/src/bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc6dc75d1a0)
	/usr/local/go/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/local/go/src/net/textproto/reader.go:38
net/http.readRequest(0xc04e0fa0c0?)
	/usr/local/go/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc3e9e66dc0, {0x3c170b8, 0xc6288bfa80})
	/usr/local/go/src/net/http/server.go:988 +0x24a
net/http.(*conn).serve(0xc3e9e66dc0, {0x3c17160, 0xc0014a0690})
	/usr/local/go/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db

goroutine 256485 [runnable]:
internal/poll.runtime_pollWait(0x7f6ccd7737b8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc1cf51fa00?, 0xc87cf00000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc1cf51fa00, {0xc87cf00000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc1cf51fa00, {0xc87cf00000?, 0x4d9586?, 0xc0003a9958?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc1f089e508, {0xc87cf00000?, 0x0?, 0x0?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc3a3e80fc0, {0xc87cf00000, 0x1000, 0x1000})
	/usr/local/go/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc8762e29c0)
	/usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc8762e29c0, 0x4)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*conn).readRequest(0xc77e02abe0, {0x3c170b8, 0xc41ce2dbc0})
	/usr/local/go/src/net/http/server.go:985 +0x1f8
net/http.(*conn).serve(0xc77e02abe0, {0x3c17160, 0xc0014a0690})
	/usr/local/go/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db

```

**Comment by prabhatsharma** [comment]
by any chance are yo u storing your data in s3?

**Comment by amirEBD** [comment]
No it's on the disk.

**Comment by amirEBD** [comment]
![image](https://user-images.githubusercontent.com/43447336/187649415-2d7bd043-21f2-4c53-a3d9-2c124c85a65b.png)
Currently resource usage
High cpu usages which fluctuates much can be seen!

**Comment by amirEBD** [comment]
```
goroutine 69727 [chan receive]:
github.com/klauspost/compress/zstd.(*Decoder).DecodeAll(0xc000a821c0, {0x7f47be35ed87, 0xf, 0x16a76}, {0xc5d4827420, 0x0, 0x1e})
	/go/pkg/mod/github.com/klauspost/compress@v1.15.9/zstd/decoder.go:313 +0xce
github.com/blugelabs/ice/compress.ZSTDDecompress({0xc5d4827420?, 0x7f50d1595538?, 0x18?}, {0x7f47be35ed87?, 0xc46b55e558?, 0x0?})
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/compress/zstd.go:44 +0x92
github.com/blugelabs/ice/compress.Decompress({0xc5d4827420?, 0x18?, 0x1513de0?}, {0x7f47be35ed87?, 0xc145d6f080?, 0xa4980b?})
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/compress/compress.go:37 +0x3f
github.com/blugelabs/ice.(*chunkedIntDecoder).loadChunk(0xc5b54364d0, 0x500000000?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/intdecoder.go:94 +0xb6
github.com/blugelabs/ice.(*PostingsIterator).loadChunk(0xc5c5eeb500, 0x0)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:348 +0x37
github.com/blugelabs/ice.(*PostingsIterator).nextDocNumAtOrAfterClean(0xc5c5eeb500, 0x0)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:629 +0x225
github.com/blugelabs/ice.(*PostingsIterator).nextDocNumAtOrAfter(0xc5c5eeb500, 0x0)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:541 +0x125
github.com/blugelabs/ice.(*PostingsIterator).nextAtOrAfter(0xc5c5eeb500, 0x7f50d1595538?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:461 +0x33
github.com/blugelabs/ice.(*PostingsIterator).Next(...)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:448
github.com/blugelabs/ice.mergeTermFreqNormLocs(0xc5d3eb5b80?, 0xa?, {0xc4c11a1b90, 0x12, 0xc145d6f680?}, 0xc145d6f680?, 0xc145d6f5e8?, 0xc420c18fe0?, {0x0, 0x0, ...}, ...)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:580 +0x73
github.com/blugelabs/ice.persistMergedRestField({0xc40cbac230?, 0xa6d16e?, 0x8?}, {_, _, _}, _, {0xc0c39ab380, 0xa, 0x10}, ...)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:320 +0x869
github.com/blugelabs/ice.persistMergedRest({0xc40cbac230, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, {0xc402f33860, 0xd, 0x4?}, 0xc145d6f850, ...)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:232 +0x58b
github.com/blugelabs/ice.mergeToWriter({0xc40cbac230?, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, 0xcbac230?, 0x0?, 0xc5143b0000?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:139 +0x2d7
github.com/blugelabs/ice.mergeSegmentBasesWriter({0xc40cbac230, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, {0x3c01b80?, 0xc40450bb40}, 0x401, 0xc3f15ccc60)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:97 +0xfd
github.com/blugelabs/ice.merge({0xc40453cb40, 0xa, 0xa7a171?}, {0xc40cbac190, 0xa, 0xa}, {0x3c01b80, 0xc40450bb40}, 0xc47acc8488?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:86 +0xba
github.com/blugelabs/ice.(*Merger).WriteTo(0xc40cbac1e0, {0x3c060a0?, 0xc47acc8488?}, 0x169eddb?)
	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:49 +0x14d
github.com/blugelabs/bluge/index.(*FileSystemDirectory).Persist(0xc3ff07aac0, {0x169eddb, 0x4}, 0xc40cbac190?, {0x7f50a9af1190, 0xc40cbac1e0}, 0x100000?)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/directory_fs.go:124 +0x1bb
github.com/blugelabs/bluge/index.(*Writer).merge(0xc2a5866900, {0xc40453cb40?, 0xc40cbac0f0?, 0x14?}, {0xc40cbac190?, 0x38?, 0x8?}, 0x4?)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:368 +0xb5
github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0xc2a5866900, 0xc40bbfce40, 0xc40cb9eb88)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:144 +0x125
github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0xc2a5866900, 0x0?, 0xc3ffcaf600, {0xa, 0xf4240, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...})
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:118 +0x305
github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0xc2a5866900, 0xc25cc16f00?, 0xc25cc16f60?)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:56 +0x257
created by github.com/blugelabs/bluge/index.OpenWriter
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:131 +0x83b

goroutine 69661 [select, 1 minutes]:
github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
github.com/blugelabs/bluge/index.OpenWriter.func1()
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
created by github.com/blugelabs/bluge/index.defaultConfig.func2
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19

goroutine 69662 [select, 1 minutes]:
github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
github.com/blugelabs/bluge/index.OpenWriter.func1()
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
created by github.com/blugelabs/bluge/index.defaultConfig.func2
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19

goroutine 69663 [select, 1 minutes]:
github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
github.com/blugelabs/bluge/index.OpenWriter.func1()
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
created by github.com/blugelabs/bluge/index.defaultConfig.func2
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19

goroutine 69664 [select, 1 minutes]:
github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
github.com/blugelabs/bluge/index.OpenWriter.func1()
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
created by github.com/blugelabs/bluge/index.defaultConfig.func2
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19

goroutine 70020 [select, 1 minutes]:
github.com/blugelabs/bluge/index.(*Writer).introducerLoop(0xc3145df680, 0xc4109586c0, 0xc410958720, 0xc410958780, 0xc3f9167ec0, 0xc5042b9da0?)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/introducer.go:51 +0x185
created by github.com/blugelabs/bluge/index.OpenWriter
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:127 +0x6f3

goroutine 70021 [select, 1 minutes]:
github.com/blugelabs/bluge/index.(*Writer).persisterLoop(0xc3145df680, 0x0?, 0xc04c359fd0?, 0xa8f06f?, 0xc3f9167f20, 0xd7)
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/persister.go:47 +0x226
created by github.com/blugelabs/bluge/index.OpenWriter
	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:129 +0x7b5

```

**Comment by amirEBD** [comment]
This log is repeating constantly

**Comment by amirEBD** [comment]
> ```
> goroutine 69727 [chan receive]:
> github.com/klauspost/compress/zstd.(*Decoder).DecodeAll(0xc000a821c0, {0x7f47be35ed87, 0xf, 0x16a76}, {0xc5d4827420, 0x0, 0x1e})
> 	/go/pkg/mod/github.com/klauspost/compress@v1.15.9/zstd/decoder.go:313 +0xce
> github.com/blugelabs/ice/compress.ZSTDDecompress({0xc5d4827420?, 0x7f50d1595538?, 0x18?}, {0x7f47be35ed87?, 0xc46b55e558?, 0x0?})
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/compress/zstd.go:44 +0x92
> github.com/blugelabs/ice/compress.Decompress({0xc5d4827420?, 0x18?, 0x1513de0?}, {0x7f47be35ed87?, 0xc145d6f080?, 0xa4980b?})
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/compress/compress.go:37 +0x3f
> github.com/blugelabs/ice.(*chunkedIntDecoder).loadChunk(0xc5b54364d0, 0x500000000?)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/intdecoder.go:94 +0xb6
> github.com/blugelabs/ice.(*PostingsIterator).loadChunk(0xc5c5eeb500, 0x0)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:348 +0x37
> github.com/blugelabs/ice.(*PostingsIterator).nextDocNumAtOrAfterClean(0xc5c5eeb500, 0x0)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:629 +0x225
> github.com/blugelabs/ice.(*PostingsIterator).nextDocNumAtOrAfter(0xc5c5eeb500, 0x0)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:541 +0x125
> github.com/blugelabs/ice.(*PostingsIterator).nextAtOrAfter(0xc5c5eeb500, 0x7f50d1595538?)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:461 +0x33
> github.com/blugelabs/ice.(*PostingsIterator).Next(...)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/posting.go:448
> github.com/blugelabs/ice.mergeTermFreqNormLocs(0xc5d3eb5b80?, 0xa?, {0xc4c11a1b90, 0x12, 0xc145d6f680?}, 0xc145d6f680?, 0xc145d6f5e8?, 0xc420c18fe0?, {0x0, 0x0, ...}, ...)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:580 +0x73
> github.com/blugelabs/ice.persistMergedRestField({0xc40cbac230?, 0xa6d16e?, 0x8?}, {_, _, _}, _, {0xc0c39ab380, 0xa, 0x10}, ...)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:320 +0x869
> github.com/blugelabs/ice.persistMergedRest({0xc40cbac230, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, {0xc402f33860, 0xd, 0x4?}, 0xc145d6f850, ...)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:232 +0x58b
> github.com/blugelabs/ice.mergeToWriter({0xc40cbac230?, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, 0xcbac230?, 0x0?, 0xc5143b0000?)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:139 +0x2d7
> github.com/blugelabs/ice.mergeSegmentBasesWriter({0xc40cbac230, 0xa, 0xa}, {0xc40cbac190, 0xa, 0xa}, {0x3c01b80?, 0xc40450bb40}, 0x401, 0xc3f15ccc60)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:97 +0xfd
> github.com/blugelabs/ice.merge({0xc40453cb40, 0xa, 0xa7a171?}, {0xc40cbac190, 0xa, 0xa}, {0x3c01b80, 0xc40450bb40}, 0xc47acc8488?)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:86 +0xba
> github.com/blugelabs/ice.(*Merger).WriteTo(0xc40cbac1e0, {0x3c060a0?, 0xc47acc8488?}, 0x169eddb?)
> 	/go/pkg/mod/github.com/zinclabs/ice@v1.1.3/merge.go:49 +0x14d
> github.com/blugelabs/bluge/index.(*FileSystemDirectory).Persist(0xc3ff07aac0, {0x169eddb, 0x4}, 0xc40cbac190?, {0x7f50a9af1190, 0xc40cbac1e0}, 0x100000?)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/directory_fs.go:124 +0x1bb
> github.com/blugelabs/bluge/index.(*Writer).merge(0xc2a5866900, {0xc40453cb40?, 0xc40cbac0f0?, 0x14?}, {0xc40cbac190?, 0x38?, 0x8?}, 0x4?)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:368 +0xb5
> github.com/blugelabs/bluge/index.(*Writer).executeMergeTask(0xc2a5866900, 0xc40bbfce40, 0xc40cb9eb88)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:144 +0x125
> github.com/blugelabs/bluge/index.(*Writer).planMergeAtSnapshot(0xc2a5866900, 0x0?, 0xc3ffcaf600, {0xa, 0xf4240, 0x4024000000000000, 0xa, 0x7d0, 0x4000000000000000, 0x0, ...})
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:118 +0x305
> github.com/blugelabs/bluge/index.(*Writer).mergerLoop(0xc2a5866900, 0xc25cc16f00?, 0xc25cc16f60?)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/merge.go:56 +0x257
> created by github.com/blugelabs/bluge/index.OpenWriter
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:131 +0x83b
> 
> goroutine 69661 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
> github.com/blugelabs/bluge/index.OpenWriter.func1()
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
> created by github.com/blugelabs/bluge/index.defaultConfig.func2
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19
> 
> goroutine 69662 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
> github.com/blugelabs/bluge/index.OpenWriter.func1()
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
> created by github.com/blugelabs/bluge/index.defaultConfig.func2
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19
> 
> goroutine 69663 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
> github.com/blugelabs/bluge/index.OpenWriter.func1()
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
> created by github.com/blugelabs/bluge/index.defaultConfig.func2
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19
> 
> goroutine 69664 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.analysisWorker(0xc40b9c7560, 0xc40b9c75c0)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:549 +0x7f
> github.com/blugelabs/bluge/index.OpenWriter.func1()
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:69 +0x2f
> created by github.com/blugelabs/bluge/index.defaultConfig.func2
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/config.go:215 +0x19
> 
> goroutine 70020 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.(*Writer).introducerLoop(0xc3145df680, 0xc4109586c0, 0xc410958720, 0xc410958780, 0xc3f9167ec0, 0xc5042b9da0?)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/introducer.go:51 +0x185
> created by github.com/blugelabs/bluge/index.OpenWriter
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:127 +0x6f3
> 
> goroutine 70021 [select, 1 minutes]:
> github.com/blugelabs/bluge/index.(*Writer).persisterLoop(0xc3145df680, 0x0?, 0xc04c359fd0?, 0xa8f06f?, 0xc3f9167f20, 0xd7)
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/persister.go:47 +0x226
> created by github.com/blugelabs/bluge/index.OpenWriter
> 	/go/pkg/mod/github.com/amir!e!b!d/bluge@v1.1.7/index/writer.go:129 +0x7b5
> ```

This log is happening repeatedley

**Comment by amirEBD** [comment]
This log is happening repeatedley. @hengfeiyang

**Comment by hengfeiyang** [comment]
Yeah, i am not sure what happened, Can you provide this machine information, let me do some debug?
