### ISSUE TITLE
Synchronize UI state with the URL

### ISSUE THREAD

**Issue by laurivosandi** [zinclabs/zincsearch#518]
**Is your feature request related to a problem? Please describe.**
Sharing search results with others is tricky because the UI state is disjoint from the URL

**Describe the solution you'd like**
The URL could be copypastable so Zinc returns the same UI state for link recipient.

**Comment by hengfeiyang** [comment]
@laurivosandi i think we can sync something in URL let share is easy.

1. selected index
2. query string
3. time range

Do you think this is ok?

**Comment by jonasgeiregat** [comment]
I can tackle this one!

**Comment by laurivosandi** [comment]
For starters this would be excellent!

**Comment by danieltaub96** [comment]
it's very important feature, to move from es towards zinc

**Comment by prabhatsharma** [comment]
not in roadmap
