### ISSUE TITLE
Ingest json data from s3

### ISSUE THREAD

**Issue by FizzaAbid** [zinclabs/zincsearch#530]
Additionally, all jobs dump data into s3 and for cloud, companies don't use internal instance storage but s3 and downloading data on internal storage will downgrade the performance. Please introduce this feature.

**Comment by hengfeiyang** [comment]
Your mean, your data was store in s3, you need download data from s3 then ingest to zinc.

If there is a way no need download, just ingest data from s3?

**Comment by hengfeiyang** [comment]
Also s3 support is primarily for log search as opposed to app search which is a better use case for zincobserve.

https://github.com/zinclabs/zincobserve
