### ISSUE TITLE
minio https access

### ISSUE THREAD

**Issue by badsmoke** [zinclabs/zincsearch#598]
Hello

our minio instance runs under https

when i set storage.domain.tld 
I get the message that the requests are redirected.
(our nginx redirect port 80 automatically to 443 https)

`"message":"Persist: failed to write object: <html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>"}`

if i set storage.domain.tld:443 i get the message that

`"message":"Persist: failed to write object: <html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>"}`

furthermore, storage.domain.tld/storage/dns does not is addressed but only: `storage/dns/`

`"Stats: MinIO ListObjectsV2 call made for Stats MinIO://storage/dns/1SHgpBjFJAc/000000"}`

Environment Variable | Default Value | Mandatory | Description
-- | -- | -- | --
ZINC_MINIO_ENDPOINT | - | No | storage.domain.tld
ZINC_MINIO_ACCESS_KEY_ID | - | No | zinc
ZINC_MINIO_SECRET_ACCESS_KEY | - | No | secret
ZINC_MINIO_BUCKET | - | No | storage

zinc runs in a k3s cluster, and so far works fully functional.

minio is accessible from the cluster

**Comment by hengfeiyang** [comment]
Also s3 support is primarily for log search as opposed to app search which is a better use case for zincobserve.

https://github.com/zinclabs/zincobserve
