### ISSUE TITLE
request minio fail

### ISSUE THREAD

**Issue by zadair** [zinclabs/zincsearch#603]
in pkg/bluge/directory/minio.go  func  Persist，buf.Len() and size is not match，size = buf.Len

otherwise

{"level":"debug","time":"2022-10-13T16:57:30+08:00","message":"Persist: failed to write object: Put \"http://127.0.0.1:19000/testzinc/test_zinc_to_minio/1SKBvsBekxi/000000/000000000014.snp\": readfrom tcp 127.0.0.1:40935->127.0.0.1:19000: http: ContentLength=106 with Body length 0"}

{"level":"debug","time":"2022-10-13T16:57:30+08:00","message":"Warning: MinIO object testzinc/test_zinc_to_minio/1SKBvsBekxi/000000/00000000000e.seg has incorrect checksum"}

**Comment by hengfeiyang** [comment]
We are marked minio & s3 deprecate
