### ISSUE TITLE
I search 广州 for the items containning 广州 not for some other words containing 州 like 惠州

### ISSUE THREAD

**Issue by hick** [zinclabs/zincsearch#625]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
search the chinese keywords in common sence way(like search 广州 for results only containing 广州 but not 惠州)

**What action did you take?**
I add "set ZINC_PLUGIN_GSE_ENABLE=true" before start the zinc.exe in windows, and then add some data in chinese as for following:
```
    { "Author": "姓名", "City": "广州", "Year": 2000 },
    { "Author": "吴广州", "City": "潮州", "Year": 1081 },
    { "Author": "姓名", "City": "海南", "Year": 1981 },
    { "Author": "hick", "City": "惠州", "Year": 2022 },
```

then I search 广州 in  http://localhost:4080/

**What action/response/output did you expect?**
the results should only contains items with 广州 but not 惠州

**What actually happened?**
the results have "惠州",  and the results of "广州" are not in the front of the results list

**What version of ZincSearch are you using?**
zinc 0.3.3

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
I've seen the https://github.com/zinclabs/zinc/pull/111 and  https://github.com/hengfeiyang/zinc-analysis-gse  Maybe I should set ZINC_PLUGIN_GSE_DICT_PATH ? but I do not know what should I put in the directory "./plugins/gse/dict" ?   It seems like to by some files like "${ZINC_PLUGIN_GSE_DICT_PATH}/user.txt" "${ZINC_PLUGIN_GSE_DICT_PATH}/user.txt" " ${ZINC_PLUGIN_GSE_DICT_PATH}/stop.txt",   but I can not understand the relations to  https://github.com/go-ego/gse/tree/master/data/dict

**Any attachments/screenshots?**

![image](https://user-images.githubusercontent.com/38886/198816150-47fcb702-6270-4179-8d9e-83b5c0583480.png)

**Comment by hengfeiyang** [comment]
you can follow this article to check again: https://mp.weixin.qq.com/s/g9fcKNSEHqwiK8Tt3MY3GA
