### ISSUE TITLE
how use range filter by `_score`

### ISSUE THREAD

**Issue by cevin** [zinclabs/zincsearch#706]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

use ES dsl search results  ` _score > N`

**What action did you take?**
```json

{
    "query": {
        "bool": {
            "filter": {
                "range": {
                    "_score": {
                        "gt": 50.1
                    }
                }
            }
        }
    },
    "from": 0,
    "size": 2,
    "sort": [
        "-_score"
    ],
    "aggs": {
        "status": {
            "terms": {
                "field": "status"
            }
        },
        "type": {
            "terms": {
                "field": "type"
            }
        }
    }
}

<!-- or-->
{
    "query": {
        "range": {
            "_score": {
                "gt": 50.1
            }
        }
    },
    "from": 0,
    "size": 2,
    "sort": [
        "-_score"
    ],
    "aggs": {
        "status": {
            "terms": {
                "field": "status"
            }
        },
        "type": {
            "terms": {
                "field": "type"
            }
        }
    }
}
```

**What action/response/output did you expect?**

correct search result.

**What actually happened?**

```
Array
(
    [error] => Array
        (
            [type] => x_content_parse_exception
            [reason] => [bool] failed to parse field
            [cause] => type: parsing_exception, reason: [filter] failed to parse field, cause: type: x_content_parse_exception, reason: [range] failed to parse field, cause: type: x_content_parse_exception, reason: [range] _score only support values of [numeric, time], got ""
        )

)
```

**How to reproduce the issue?**

use the DSL (maybe delete aggs)

**What version of ZincSearch are you using?**

0.3.6 linux amd64

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

No

**Any attachments/screenshots?**

NO

**Which service(s) is this relate to?**
API & PHP CURL

**Comment by hengfeiyang** [comment]
Not supported yet.
