### ISSUE TITLE
Fake s3

### ISSUE THREAD

**Issue by gedw99** [zinclabs/zincsearch#74]
https://github.com/johannesboyne/gofakes3

To allow testing

**Comment by prabhatsharma** [comment]
I have [MinIO](https://github.com/minio/minio) implementation planned. Should be able to add soon. Won't need gofakes3 then.

**Comment by gedw99** [comment]
fakes3 if for when you are using Minio. Used for testing.

**Comment by prabhatsharma** [comment]
Closing this issue. Look at https://github.com/zinclabs/zincsearch/issues/782 for explanation.

**Comment by hengfeiyang** [comment]
We are mark s3 & minIO deprecated, if you use zincSearch for log, you can try ZincObserve https://github.com/zinclabs/zincobserve

**Comment by gedw99** [comment]
thanks @hengfeiyang the explanation makes total sense.

I am using zinc for app search, not log search.
