### ISSUE TITLE
In windows, I have created env file to store username and password, but the UI shows "Invalid Credentials" 

### ISSUE THREAD

**Issue by AkashSCIENTIST** [zinclabs/zincsearch#809]
![Screenshot (188)](https://user-images.githubusercontent.com/25793714/225053823-4d25cd17-3620-4d8e-b932-044dea3782b1.png)

**Comment by hengfeiyang** [comment]
How did you set the env file?

**Comment by AkashSCIENTIST** [comment]
In the same folder where .exe file exists. Content of .env file :
```
ZINC_FIRST_ADMIN_USER=admin
ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
```

**Comment by AkashSCIENTIST** [comment]
I deleted the data folder and restarted the application, it worked. Thank you 😀
