### ISSUE TITLE
I have a string which is 123,456,789. Search 456 Unable to match content

### ISSUE THREAD

**Issue by yangtze64** [zinclabs/zincsearch#820]
![image](https://user-images.githubusercontent.com/14882119/226562121-d3b5c9bc-0ae6-4773-a9b3-37cfa6d9f6c8.png)

**Comment by hengfeiyang** [comment]
The `123,456,789` is a valid integer, so it will no split, just one token.if you want to split it by `,` you need to use other analyzer.
