### ISSUE TITLE
Documentation may be a little misleading

### ISSUE THREAD

**Issue by vituchon** [zinclabs/zincsearch#827]
Hi there!

I'm studying how to use zincsearch, and when I click here

![image](https://user-images.githubusercontent.com/1927644/227797308-d2c4978e-1cc3-4caa-8c3b-ed2ba6cbe88d.png)

I go to zingobserve documentation. 

I guess the place to go would (using that link) would be https://zincsearch-docs.zinc.dev/.

Thanks for reading this.

If I'm wrong in something my apoligies in advanced.

Greetings

Víctor

**Comment by hengfeiyang** [comment]
@vituchon Thanks, fixed.

**Comment by vituchon** [comment]
Anytime @hengfeiyang, thanks.
I will close this issue in peace.

Until next time.
